//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportTicket
    {
        public string idImport { get; set; }
        public string idProduct { get; set; }
        public System.DateTime date { get; set; }
        public int quantity { get; set; }
        public string addressDelivery { get; set; }
        public int price { get; set; }
        public int totalPrice { get; set; }
        public string idProvider { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
