//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public string idInvoice { get; set; }
        public string idOrder { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
        public int price { get; set; }
    }
}
